### ISSUE TITLE
Error IP

### ISSUE THREAD

**Issue by barripdmx** [source-nerd/twitter-scraper#289]
Twitter_scraper_master>python main.py --searchquery github --since 2023-11-20 --until 2023-11-21 --op test.csv --log test.log
https://twitter.com/i/search/timeline?f=tweets&q=%20github%20since%3A2023-11-20%20until%3A2023-11-21&src=typd&lang=en&max_position=
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Retrying with different IP !!
Traceback (most recent call last):
  File "C:\Twitter_scraper_master\main.py", line 59, in <module>
    arg_parser(sys.argv[1:])
  File "C:\Users\barri\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\barri\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\barri\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\barri\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Twitter_scraper_master\main.py", line 52, in arg_parser
    parse_json(search_parameters)
  File "C:\Twitter_scraper_master\scraper.py", line 72, in parse_json
    json_res = get_tweets(search_params, min_position)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Twitter_scraper_master\scraper.py", line 58, in get_tweets
    json_res = response.read()
               ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'read'

**Comment by yyds-wwj** [comment]
i have the same problem, How do you say
